name: amity_uikit_beta_service
description: Amity UIkit opensource developed by SLE team to enable social feature in Flutter.
version: 3.0.2+5
homepage: https://github.com/ThanakornThanom/ThanakornThanom--flutter_amity_uikit_beta_service

environment:
  sdk: ">=2.17.6 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  animation_wrappers: ^3.0.0
  font_awesome_flutter: ^10.1.0
  pin_code_fields: ^8.0.1
  country_code_picker: ^3.0.0
  flutter_bloc: ^8.1.5
  shared_preferences: ^2.0.5
  flutter_phoenix: ^1.0.0
  flutter_launcher_icons: ^0.13.1
  modal_bottom_sheet: ^3.0.0
  amity_sdk: ^0.46.2
  provider: ^6.0.3
  carousel_slider: ^4.1.1
  chewie: ^1.3.4
  video_player: ^2.4.5
  # extended_image: ^6.2.1
  intl: ^0.19.0
  image_picker: ^1.1.2
  socket_io_client: ^1.0.0
  get_time_ago: ^1.1.5
  shimmer: ^3.0.0
  dio:
  sign_in_with_apple: ^4.1.0
  any_link_preview: ^3.0.1
  linkwell: ^2.0.6
  linkify: ^5.0.0
  flutter_link_previewer: ^3.1.0
  url_launcher: ^6.1.6
  flutter_sticky_header: ^0.6.5
  path_provider: ^2.0.2
  video_thumbnail: ^0.5.3
  mime: ^1.0.4
  file_picker: ^6.0.0
  open_file: ^3.3.2
  flutter_svg: ^2.0.9
  permission_handler: ^11.0.1
  intrinsic_dimension: ^0.3.1
  flutter_linkify: ^6.0.0





dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:
  # This section identifies this Flutter project as a plugin project.
  # The 'pluginClass' specifies the class (in Java, Kotlin, Swift, Objective-C, etc.)
  # which should be registered in the plugin registry. This is required for
  # using method channels.
  # The Android 'package' specifies package in which the registered class is.
  # This is required for using method channels on Android.
  # The 'ffiPlugin' specifies that native code should be built and bundled.
  # This is required for using `dart:ffi`.
  # All these are used by the tooling to maintain consistency when
  # adding or updating assets for this project.
  plugin:
    platforms:
    # This plugin project was generated without specifying any
    # platforms with the `--platform` argument. If you see the `some_platform` map below, remove it and
    # then add platforms following the instruction here:
    # https://flutter.dev/docs/development/packages-and-plugins/developing-packages#plugin-platforms
    # -------------------
      some_platform:
        pluginClass: somePluginClass
    # -------------------

  # To add assets to your plugin package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg
  assets:
    - assets/images/IMG_5637.JPG
    - assets/images/fileType/
    - assets/Icons/
    - assets/images/Icon name.png
    - assets/images/user_placeholder.png
    - assets/images/noPostYet.png
    - assets/images/privateIcon.png
    - assets/images/noVideo.png
    - assets/config/config.json
    - assets/



  # For details regarding assets in packages, see
  # https://flutter.dev/assets-and-images/#from-packages
  #
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # To add custom fonts to your plugin package, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Material-Design-Iconic-Font
      fonts:
        - asset: assets/fonts/Material-Design-Iconic-Font.ttf

  #
  # For details regarding fonts in packages, see
  # https://flutter.dev/custom-fonts/#from-packages
